server:
  port: 8080
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmetserdargeze/configserver-medium-tutorial.git
    profiles:
      active: test
management:
  security:
    enabled: false